CREATE TABLE IF NOT EXISTS transactions (
  id VARCHAR(255) PRIMARY KEY,
  item VARCHAR(255) NOT NULL,
  date VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Reserved',
  amount VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);